<?xml version="1.0" encoding="utf-8"?><Database Name="ASPDatabase" Class="CookbookDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-841L133;Initial Catalog=ASPDatabase;Integrated Security=True" SettingsObjectName="DbConnection.Properties.Settings" SettingsPropertyName="ASPDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="users">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="roleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="roles_users" Member="roles" ThisKey="roleId" OtherKey="Id" Type="roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.recipes" Member="recipes">
    <Type Name="recipes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="roles">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="roles_users" Member="users" ThisKey="Id" OtherKey="roleId" Type="users" />
    </Type>
  </Table>
</Database>